### ISSUE TITLE
Backport to 1.16

### ISSUE THREAD

**Issue by denzuko** [altrisi/DropFullCarts#3]
Any chance we can get a backport to 1.16? Or would we accept pull requests if one is provided?

**Comment by altrisi** [comment]
Sorry for the late reply, I'm currently a bit busy with final exams at university.

But yes, it's possible to backport it and I know exactly what would be needed. Only reason it doesn't support it is because what I did was testing what was the earlier version that worked without changes to the implementation I made in 1.18.2.

I'll do it after all exams are finished if I don't forget (or earlier if I get too tired).

**Comment by altrisi** [comment]
It's out! Sorry if it's too late, I haven't had a lot of time lately.
Here's the direct link to the new version on Curseforge: https://www.curseforge.com/minecraft/mc-mods/dropfullcarts/files/3844933
